source "http://api.berkshelf.com"

# Base
cookbook 'build-essential',
	:git => 'https://github.com/opscode-cookbooks/build-essential'

cookbook 'git',
	:git => 'http://github.com/opscode-cookbooks/git'

cookbook 'sqlite',
	:git => 'https://github.com/opscode-cookbooks/sqlite'

cookbook 'MailCatcher',
	:git => 'https://github.com/bryantebeek/chef-mailcatcher'

cookbook 'graphicsmagick',
	:git => 'https://github.com/jousch/chef-graphicsmagick',
	:ref => 'v1.0.0'

cookbook 'apache2'

